package com.farmacia.prototipo.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import com.farmacia.prototipo.view.Inventario;

/**
 *
 * @author Samantha Moreira
 */
public class Dashboard extends javax.swing.JFrame {

    private final Inventario panelInventario = new Inventario();

    public Dashboard() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        mostrarPanel(panelInventario);
    }

    private void mostrarPanel(JPanel panel) {
        jpContenedor.removeAll();
        jpContenedor.add(panel, BorderLayout.CENTER);
        jpContenedor.revalidate();
        jpContenedor.repaint();
    }

    public Dashboard(JButton btnInventario, JButton btnVentas, JPanel jPanel1, JPanel jPanel2, JPanel jpContenedor, JPanel jpOpciones, JLabel lbLogo) throws HeadlessException {
        this.btnInventario = btnInventario;
        this.btnVentas = btnVentas;
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.jpContenedor = jpContenedor;
        this.jpOpciones = jpOpciones;
        this.lbLogo = lbLogo;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jpContenedor1 = new javax.swing.JPanel();
        jpOpciones1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbLogo1 = new javax.swing.JLabel();
        btnVentas1 = new javax.swing.JButton();
        btnInventario1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpContenedor = new javax.swing.JPanel();
        jpOpciones = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1600, 800));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor1.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor1.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jpContenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1400, 810));

        jpOpciones1.setBackground(new java.awt.Color(255, 255, 255));
        jpOpciones1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpOpciones1.setForeground(new java.awt.Color(255, 255, 255));
        jpOpciones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomini.png"))); // NOI18N
        jPanel4.add(lbLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 46));

        jpOpciones1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        btnVentas1.setBackground(new java.awt.Color(255, 255, 255));
        btnVentas1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnVentas1.setForeground(new java.awt.Color(51, 51, 51));
        btnVentas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        btnVentas1.setText(" Ventas");
        btnVentas1.setBorderPainted(false);
        btnVentas1.setContentAreaFilled(false);
        btnVentas1.setFocusPainted(false);
        btnVentas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentas1MouseExited(evt);
            }
        });
        btnVentas1.addActionListener(this::btnVentas1ActionPerformed);
        jpOpciones1.add(btnVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 40));

        btnInventario1.setBackground(new java.awt.Color(255, 255, 255));
        btnInventario1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnInventario1.setForeground(new java.awt.Color(51, 51, 51));
        btnInventario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario-disponible_1.png"))); // NOI18N
        btnInventario1.setText(" Inventario");
        btnInventario1.setBorderPainted(false);
        btnInventario1.setContentAreaFilled(false);
        btnInventario1.setFocusPainted(false);
        btnInventario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventario1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventario1MouseExited(evt);
            }
        });
        btnInventario1.addActionListener(this::btnInventario1ActionPerformed);
        jpOpciones1.add(btnInventario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 40));

        jPanel3.add(jpOpciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1612, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor.setLayout(new java.awt.BorderLayout());

        jpOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jpOpciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpOpciones.setForeground(new java.awt.Color(255, 255, 255));
        jpOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomini.png"))); // NOI18N
        jPanel2.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 46));

        jpOpciones.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        btnVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnVentas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(51, 51, 51));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        btnVentas.setText(" Ventas");
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setFocusPainted(false);
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
        });
        btnVentas.addActionListener(this::btnVentasActionPerformed);
        jpOpciones.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 40));

        btnInventario.setBackground(new java.awt.Color(255, 255, 255));
        btnInventario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(51, 51, 51));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario-disponible_1.png"))); // NOI18N
        btnInventario.setText(" Inventario");
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setFocusPainted(false);
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventarioMouseExited(evt);
            }
        });
        btnInventario.addActionListener(this::btnInventarioActionPerformed);
        jpOpciones.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 40));

        jpContenedor.add(jpOpciones, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1400, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1610, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        // TODO add your handling code here:}
        btnVentas.setForeground(new Color(0, 123, 255));
        btnVentas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        // TODO add your handling code here:
        btnVentas.setForeground(new Color(60, 60, 60));
        // Vuelve el cursor a la flecha por defecto
        btnVentas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseEntered
        // TODO add your handling code here:
        btnInventario.setForeground(new Color(0, 123, 255));
        btnInventario.setCursor(new Cursor(Cursor.HAND_CURSOR)); //Cambia el cursor para indicar que es clickeable
    }//GEN-LAST:event_btnInventarioMouseEntered

    private void btnInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseExited
        // TODO add your handling code here:
        btnInventario.setForeground(new Color(60, 60, 60));
        // Vuelve el cursor a la flecha por defecto
        btnInventario.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnInventarioMouseExited

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        mostrarPanel(panelInventario);

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnVentas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentas1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentas1MouseEntered

    private void btnVentas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentas1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentas1MouseExited

    private void btnVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentas1ActionPerformed

    private void btnInventario1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventario1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventario1MouseEntered

    private void btnInventario1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventario1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventario1MouseExited

    private void btnInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnInventario1;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVentas1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpContenedor1;
    private javax.swing.JPanel jpOpciones;
    private javax.swing.JPanel jpOpciones1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogo1;
    // End of variables declaration//GEN-END:variables
}
