package com.farmacia.prototipo.view;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario-PC
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbUsuario1 = new javax.swing.JLabel();
        btInicioSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setForeground(new java.awt.Color(0, 0, 0));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoFarm.png"))); // NOI18N
        lbLogo.setPreferredSize(new java.awt.Dimension(560, 180));
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        lbUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lbUsuario.setText(" Contraseña");
        lbUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel1.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 400, 40));

        lbUsuario1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        lbUsuario1.setText(" Usuario");
        lbUsuario1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel1.add(lbUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 400, 40));

        btInicioSesion.setBackground(new java.awt.Color(240, 28, 35));
        btInicioSesion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        btInicioSesion.setText("Iniciar Sesión");
        btInicioSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btInicioSesion.setBorderPainted(false);
        btInicioSesion.setFocusPainted(false);
        btInicioSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btInicioSesion.addActionListener(this::btInicioSesionActionPerformed);
        jPanel1.add(btInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioSesionActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInicioSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbUsuario1;
    // End of variables declaration//GEN-END:variables
}
